spring.application.name=payroll
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.use-hateoas=false  # Add this line

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hmaysaa333@gmail.com
spring.mail.password=cakd igxz xrca ozsj 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


